version: "3.7"

services:
    php8-fpm:
        container_name: php81-fpm-project17
        image: my-images/php81-fpm-alpine:0.1
        restart: always
        volumes:
            - /home/docker/projects/17_testing_Laravel10:/usr/share/nginx/html # Docker toolbox + VirtualBox
            # - ../:/usr/share/nginx/html # Docker desktop + WSL2
        networks:
            - backEnd-network

    nginx:
        container_name: nginx-project17
        env_file: .env
        image: my-images/nginx124-alpine:0.1
        volumes:
            - /home/docker/projects/17_testing_Laravel10:/usr/share/nginx/html # Docker toolbox + VirtualBox
            # - ../:/usr/share/nginx/html # Docker desktop + WSL2
        ports:
            - ${PROJECT_PORT}:${PORT}
        networks:
            - backEnd-network
        links:
            - php8-fpm

    postgresql:
        container_name: postgresql-project17
        image: my-images/postgresql15-alpine:0.1
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            - backEnd-network

networks:
    backEnd-network:
        name: Custom-BackEnd-Network
        driver: bridge

volumes:
    pgdata:
        name: "pgdata_17_testing_Laravel10" ## cambiar por pgdata_<nombre-carpeta-proyecto>
        external: false
